name: Build-and-Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      configuration: release

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore  --configuration ${{ env.configuration }}
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration ${{ env.configuration }}

      - name: Publish 
        run: dotnet publish --configuration ${{ env.configuration }} --output ${{runner.temp }}/artifact
      - name: Upload the build artifact
        uses: actions/upload-artifact@v4
        with: 
          name: publish
          path: ${{ runner.temp }}/artifact